### ISSUE TITLE
[GW] speed-up the computation

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-science-portal#461]
## Status

The crossmatch performances are absurdly bad beyond the arcminute level.

| center (equatorial) | radius | time (second) |
|---------|-------------------|-----------------|
|  (193.822, 2.89732) | 5 arcsecond | min: 0.21, mean: 0.26, max: 0.40 | 
|  (193.822, 2.89732) | 1 arcmin | min: 0.41, mean: 0.73, max: 1.98 |
|  (193.822, 2.89732) | 1 degree | min: 60.02, mean: 60.07, max: 60.11  |
|  (347.3841674, -6.6390054) | 5 arcsecond | min: 0.24, mean: 0.54, max: 0.97 | 
|  (347.3841674, -6.6390054) | 1 arcmin | min: 0.47, mean: 1.20, max: 3.48 |
|  (347.3841674, -6.6390054) | 1 degree | min: 60.02, mean: 60.04, max: 60.06  |

Moreover it freezes the portal for large queries with:

```
Traceback (most recent call last):
  File "HBaseClient.java", line 241, in com.Lomikel.HBaser.HBaseClient.scan
  File "HBaseClient.java", line 300, in com.Lomikel.HBaser.HBaseClient.scan
  File "HBaseClient.java", line 504, in com.Lomikel.HBaser.HBaseClient.scan
  File "ResultScanner.java", line 55, in org.apache.hadoop.hbase.client.ResultScanner$1.hasNext
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/miniconda/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/miniconda/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/miniconda/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/miniconda/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/miniconda/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centos/fink-science-portal/apps/api/api.py", line 654, in query_db
    pdfs = return_explorer_pdf(payload, user_group)
  File "/home/centos/fink-science-portal/apps/api/utils.py", line 292, in return_explorer_pdf
    0, True, True
java.io.java.io.UncheckedIOException: java.io.UncheckedIOException: java.io.IOException: Failed to get result within timeout, timeout=60000ms
```

Not only this, but search for GW counterpart is completely useless for large sky fractions. The current strategy involves 2 steps:
- Q1: given a list of sky pixels, query the table of pixels to find all object IDs falling inside those pixels
- Q2: given a list of object IDs, query the master table to retrieve data

Current performances:

| Event | credible level | sky fraction | Q1 | Q2 |
|---------|-------------------|-----------------|------|------|
|  S200219ac | 0.1 | 34 deg2 | 10 sec | 10 sec |
|  S230529ay | 0.1 | 1266 deg2 | 60 sec | inf | 
 
Note that there are cache effects taking place. The second time Q1 or Q2 is re-run, the results come back faster. But in practice this is useless, as a user will not perform the query several times... So this is clearly not scalable with the sky fraction. 

### Reducing the number of columns

`Q1` is usually fast because the pixel table is very thin (the row key column + one ID column), but `Q2` scales very badly if there are many matches as it retrieves _all data_ for _all matching objects_. Let's use `"i:objectId,i:jd,i:magpsf,i:ra,i:dec,d:cdsxmatch"`:

| Event | credible level | sky fraction | time |
|---------|-------------------|-----------------|------------|
|  S200219ac (all columns) | 0.1 | 34 deg2 | min: 4.60, mean: 5.88, max: 8.35 |
|  S200219ac (subset) | 0.1 | 34 deg2 | min: 3.55, mean: 3.87, max: 4.21 |

Note that cache effects apply with respect to previous runs. We gain a bit though. 

### Reducing the variation time

For GW, we want events that started varying within the time boundaries. Currently, we were imposing condition on `jd` -- but `jd` just means the object has varied within the time boundaries, not that it started varying. Unfortunately the pixel table only contains information on `jd`, and not the first variation time (`jdstarthist`). **TODO: add a new column on the pixel table with the first variation time.**

### Moving from 2 steps to 1 step

The 2-step strategy is introducing a lot of overhead. HBase is not very flexible, but eventually we could imagine extending the pixel table with data we need, so that we do not have to perform the second step in the master table. **TODO: create a new pixel table with extra information.**. The current table is 9GB big (two columns only, 2019-2023 data).

What extra information do we need?
```
objectId
candid
magpsf
sigmapsf
jd
jdstarthist
cdsxmatch
finkclass (UDF)
drb
ra
dec
fid
distnr
nalerthist
```

So eventually this step would include the previous two optimisations (reducing the number of columns, and reducing the variation time). Go go go!

### Implementation

- [x] create a new index table for pixel at NSIDE 128. Ingest data yearly (make test on S230529ay). Cast data. compute fink class and rate before.
- [x] update the index table script in Fink for nightly updates.
- [x] update the science portal API part
- [ ] publish benchmarks and update documentation

**Comment by JulienPeloton** [comment]
See https://github.com/astrolabsoftware/fink-broker/pull/717

### Schema change

Now the conesearch & bayestar endpoints return a light schema including:

```
objectId
candid
magpsf
sigmapsf
jd
jdstarthist
cdsxmatch
finkclass (UDF)
drb
ra
dec
fid
distnr
nalerthist
```

In addition, for conesearch the time boundaries concern the first variation time, that is if a user specifies a starting date (UTC) and a window (in days), the alert returned will be those that _started_ varying within this time window. Idem for bayestar.

### API change

`/api/v1/bayestar` gets two new options: `days_before` and `days_after`. When running the search, Fink will return candidates that started varying within `[t0 - days_before, t0 + days_after]`, where `t0` is the GW trigger. Maximum time window is `days_after + days_before = 7`.  `days_*` are float, and must be positive.

### Conesearch

| center (equatorial) | radius | time (second) |
|---------|-------------------|-----------------|
|  (193.822, 2.89732) [old] | 1 degree | min: 60.02, mean: 60.07, max: 60.11  |
|  (193.822, 2.89732) [new] | 1 degree |  |
|  (347.3841674, -6.6390054) [old] | 1 degree | min: 60.02, mean: 60.04, max: 60.06  |
|  (347.3841674, -6.6390054) [new] | 1 degree |   |

### Bayestar

| Event | credible level | sky fraction | time |
|---------|-------------------|-----------------|------------|
|  S200219ac [old] | 0.1 | 34 deg2 | min: 4.60, mean: 5.88, max: 8.35 |
|  S200219ac [new] | 0.1 | 34 deg2 |  |
|  S230529ay [old] | 0.1 | 1266 deg2 |  infinite |
|  S230529ay [new] | 0.1 | 1266 deg2 |  |


### GW web page

To be described
